
services:
  web:
    image: rafiansyah567/caterwise-web:latest
    container_name: caterwise-web
    ports:
      - "3050:3000"
    env_file:
      - apps/web/.env
    restart: always

  api:
    image: rafiansyah567/caterwise-api:latest
    container_name: caterwise-api
    ports:
      - "8050:8000"
    env_file:
      - .env
    restart: always