
services:
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "3050:3000"
    env_file:
      - apps/web/.env
    restart: always

  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    ports:
      - "8050:8000"
    env_file:
      - .env
    restart: always